### ISSUE TITLE
outdated dump3d CS output

### ISSUE THREAD

**Issue by ojwb** [patrickbwarren/qgis3-survex-import#3]
For better compatibility with newer PROJ releases, Survex 1.4.x now usually generates `EPSG:nnnn` as the coordinate system code to store when creating .3d files, and the img library now automatically converts many of the proj4 strings which older versions generated to `EPSG:nnnn` when reading existing .3d files, so your example showing `CS +init=epsg:3042 +no_defs` will now give `CS EPSG:3042` instead.  This is the case even if you generated the .3d file with an older Survex version from before these changes!

In a similar way and for similar reasons, ESRI codes are now generated as/mapped to `ESRI:nnnn` instead of using PROJ4 strings.

Some cases will still use PROJ4 strings:

* If a custom PROJ4 string was specified (and it doesn't match one Survex generated).
* OSGB since there don't seem to be separate EPSG codes for each OSGB "tile".
* A small number of somewhat obscure coordinate systems Survex really only implements only because Therion does.  EUR79Z30 doesn't seem to have an EPSG code; some of the \*JTSK\* ones look like they might so they could probably be handled too.

BTW, if you believe the Survex "*cs" docs are "spartan", feel free to send patches to improve where you perceive them to be lacking.

**Comment by ojwb** [comment]
> * some of the *JTSK* ones look like they might so they could probably be handled too.

FWIW, I checked and the PROJ4 strings epsg.io gives for these don't seem to be equivalent.

**Comment by patrickbwarren** [comment]
This was also now a bug in the python script, now fixed by including IGNORECASE flag in the pattern match.  Documentation has been updated and streamlined.
